/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package news_aggregator;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import java.awt.Dimension;
import java.awt.Toolkit;

public class App {

    public static void main(String[] args) {

        ChromeOptions options = new ChromeOptions();
        options.setBinary("/usr/bin/google-chrome");
        options.addArguments("--disable-blink-features=AutomationControlled");
        options.addArguments(
                "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36");
        options.addArguments("--start-maximized");

        System.setProperty("webdriver.chrome.driver", "/home/user/chromedriver-linux64/chromedriver");

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = (int) screenSize.getWidth();
        int screenHeight = (int) screenSize.getHeight();

        int windowWidth = screenWidth / 2;
        int windowHeight = screenHeight;

        try {

            String query = "5g smartphones\n";

            WebDriver driver1 = new ChromeDriver(options);

            driver1.get("https://www.amazon.in");

            WebElement searchBox1 = driver1.findElement(By.id("twotabsearchtextbox"));

            searchBox1.sendKeys(query);

            Thread.sleep(2000);

            WebElement spanElement = driver1.findElement(By.id("a-autoid-0"));
            spanElement.click();

            Thread.sleep(1500);

            WebElement anchorElement = driver1.findElement(By.id("s-result-sort-select_1"));
            anchorElement.click();

            Thread.sleep(1500);

            WebDriver driver2 = new ChromeDriver(options);

            driver2.get("https://www.flipkart.in");

            try {
                WebElement closeButton = driver2.findElement(By.xpath("//button[contains(text(), '✕')]"));
                closeButton.click();
            } catch (Exception e) {
                System.out.println("No login popup found.");
            }

            WebElement searchBox2 = driver2.findElement(By.name("q"));
            searchBox2.sendKeys(query);

            Thread.sleep(1000);

            WebElement parentDiv = driver2.findElement(By.className("sHCOk2"));

            WebElement fourthChild = parentDiv.findElement(By.xpath("./*[" + 4 + "]"));

            fourthChild.click();

            Thread.sleep(1500);

            driver1.manage().window().setPosition(new org.openqa.selenium.Point(0, 0));
            driver1.manage().window().setSize(new org.openqa.selenium.Dimension(windowWidth, windowHeight));

            driver2.manage().window().setPosition(new org.openqa.selenium.Point(windowWidth + 700, 0));
            driver2.manage().window().setSize(new org.openqa.selenium.Dimension(windowWidth, windowHeight));

            JavascriptExecutor js1 = (JavascriptExecutor) driver1;
            JavascriptExecutor js2 = (JavascriptExecutor) driver2;

            js1.executeScript("window.scrollBy(250, 0);");
            js2.executeScript("window.scrollBy(300, 0);");

            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                System.out.println("Shutdown hook is running...");
                driver1.quit();
                driver2.quit();
            }));

            while (true) {
                js1.executeScript("window.scrollBy(0, 1);");
                js2.executeScript("window.scrollBy(0, 1);");
                Thread.sleep(40);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
